src/Entity/Person.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PersonRepository")
 */
class Person
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column()
     */
    private $name;

    /**
     * @ORM\Column()
     */
    private $realName;

    /**
     * @ORM\Column(type="integer")
     */
    private $highScore;

    /**
     * @ORM\Column()
     */
    private $email;

    /**
     * @var Universe
     * @ORM\ManyToOne(targetEntity="Universe")
     */
    private $universe;

    /**
     * @var string
     *
     * @ORM\Column(nullable=true)
     */
    private $tagLine;

    /**
     * @ORM\Column(nullable=true)
     */
    private $avatarFilename;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    public function setName($name)
    {
        $this->name = $name;
    }

    public function getName()
    {
        return $this->name;
    }

    public function getTagLine()
    {
        return $this->tagLine;
    }

    public function setTagLine($tagLine)
    {
        $this->tagLine = $tagLine;
    }

    public function setUniverse($affiliatedUniverse)
    {
        $this->universe = $affiliatedUniverse;
    }

    /**
     * @return Universe
     */
    public function getUniverseName()
    {
        return $this->universe ? $this->universe->getName() : '';
    }

    public function setEmail($email)
    {
        $this->email = $email;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setHighScore($highScore)
    {
        $this->highScore = $highScore;
    }

    public function getHighScore()
    {
        return $this->highScore;
    }

    public function setAvatarFilename($logoFilename)
    {
        $this->avatarFilename = $logoFilename;
    }

    public function getAvatarFilename()
    {
        return $this->avatarFilename;
    }

    public function setRealName($realName)
    {
        $this->realName = $realName;
    }

    public function getRealName()
    {
        return $this->realName;
    }
}

src/Entity/Universe.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table()
 * @ORM\Entity
 */
class Universe
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
}

src/Controller/HomePageController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use App\Repository\PersonRepository;
use App\Repository\UniverseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomePageController extends AbstractController
{
    /**
     * @Route("/")
     * @param EntityManagerInterface $entityManager
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function homepageAction(EntityManagerInterface $entityManager)
    {

        $characters =$entityManager->getRepository(Person::class)->findAll();
        //$characters = $this->getDoctrine()->getRepository(PersonRepository::class)->findAll();
            //dump($characters);
        return $this->render('Homepage/homepage.html.twig', array(
            'characters' => $characters
        ));
    }
}

templates/Homepage/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Real Name</th>
            <th>High Score</th>
            <th>Email</th>
            <th>Universe</th>
            <th>Tag Line</th>
            <th>Avatar</th>
        </tr>
        </thead>
        <tbody>
        {% for character in characters %}
            <tr>
                <td>{{ character.name }}</td>
                <td>{{ character.realName }}</td>
                <td>{{ character.highScore }}</td>
                <td>{{ character.email }}</td>
                <td>{{ character.universeName }}</td>
                <td>{{ character.tagLine }}</td>
                <td>
                    {#
                        I normally use VichUploaderBundle and its Twig
                        vich_uploader_asset() function to render the URL
                        to uploaded assets. But for simplicity, I'm just
                        hardcoding that assets live in the uploads/avatars directory
                    #}
                    {% if character.avatarFilename %}
                        <img src="{{ asset('uploads/avatars/'~character.avatarFilename) }}" alt="{{ character.name }}"/>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7" style="text-align: center;">We need to play more video games</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}KnpUniversity!{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"/>
    {% endblock %}
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
</head>
<body>
<div class="container">

    <div class="page-header">
        <h1>Alice: Fixtures Superhero</h1>
        <p class="lead">Get some ridiculous data into your app ridiculously fast</p>
    </div>

    <div class="row">
        <div class="col-md-12">
            {% block body %}{% endblock %}
        </div>
    </div>
</div>
{% block javascripts %}{% endblock %}
</body>
</html>